# Generated by Django 5.2.7 on 2025-10-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file_url', models.URLField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
